services:
  ibkr:
    build: ./app
    ports:
      - "6080:6080"
      - "8888:8888"
    restart: unless-stopped
    secrets:
      - ibkr_username
      - ibkr_password
    stop_signal: SIGKILL
    environment:
      - TWS_MAJOR_VRSN=1011

secrets:
  ibkr_username:
    file: ./username.txt
  ibkr_password:
    file: ./password.txt