services:
  ibkr:
    build:
      context: ./app
      args:
        ibc_version: 3.12.0
    ports:
      - "127.0.0.1:6080:6080"
      - "127.0.0.1:8888:8888"
    restart: unless-stopped
    secrets:
      - ibkr_username
      - ibkr_password
    stop_signal: SIGKILL
    environment:
      - TWS_MAJOR_VRSN=1011

secrets:
  ibkr_username:
    file: ./username.txt
  ibkr_password:
    file: ./password.txt
